# Generated by Django 5.0.3 on 2024-04-09 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_authmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authmodel',
            name='phone_number',
        ),
    ]
