# Generated by Django 5.0.3 on 2024-06-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_category_mobels'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobels',
            old_name='text',
            new_name='content',
        ),
    ]
