# Generated by Django 5.0.3 on 2024-06-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_text_mobels_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Text',
            field=models.CharField(max_length=500),
        ),
    ]
