# Generated by Django 5.0.3 on 2024-06-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_luxury'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Text',
            new_name='CodeTMC',
        ),
        migrations.AddField(
            model_name='category',
            name='Height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Width',
            field=models.IntegerField(null=True),
        ),
    ]
