# Generated by Django 5.0.3 on 2024-06-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_text_category_codetmc_category_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='CodeTMC',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Height',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Length',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Weight',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Width',
        ),
    ]
