# Generated by Django 5.0.3 on 2024-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_category_codetmc_remove_category_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luxury',
            name='CodeTMC1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='luxury',
            name='Height1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='luxury',
            name='Length1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='luxury',
            name='Weight1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='luxury',
            name='Width1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobels',
            name='CodeTMC',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mobels',
            name='Height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobels',
            name='Length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobels',
            name='Weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mobels',
            name='Width',
            field=models.IntegerField(null=True),
        ),
    ]
