# Generated by Django 5.0.3 on 2024-06-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_codetmc1_luxury_codetmc_category_codetmc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luxury',
            name='category',
        ),
    ]
