# Generated by Django 5.0.3 on 2024-06-18 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_luxury_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobels',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myapp.category'),
        ),
    ]
