# Generated by Django 5.0.3 on 2024-06-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_mobels_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobels',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
